# Generated by Django 3.1.5 on 2021-07-09 21:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=50)),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Event starts')),
                ('start_time', models.TimeField(default=django.utils.timezone.now, verbose_name='Time')),
                ('end_date', models.DateField(default=django.utils.timezone.now, verbose_name='Event ends')),
                ('end_time', models.TimeField(default=django.utils.timezone.now, verbose_name='Ends at')),
                ('date_published', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField(default='Description Here', verbose_name='Description')),
                ('location', models.CharField(default='', max_length=100)),
                ('author', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
