# Generated by Django 3.2.5 on 2021-07-22 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0015_edit_solarschedule_events_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fitfeed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_id', models.CharField(max_length=50)),
                ('message', models.TextField(default='Message!!', verbose_name='Message')),
                ('joke', models.BooleanField(default=False)),
                ('weather', models.BooleanField(default=False)),
                ('latitude', models.DecimalField(decimal_places=5, max_digits=8, null=True)),
                ('longitude', models.DecimalField(decimal_places=5, max_digits=8, null=True)),
                ('author', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.periodictask')),
            ],
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
