# Generated by Django 3.1.5 on 2021-03-15 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitfeed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='fit_image',
            field=models.ImageField(default='#', upload_to='media/activity_thumbnail'),
        ),
    ]
