# Generated by Django 3.1.5 on 2021-03-16 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitfeed', '0002_auto_20210315_1737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feed',
            old_name='fit_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='feed',
            old_name='datetime_feed',
            new_name='datetime',
        ),
        migrations.RenameField(
            model_name='feed',
            old_name='fit_duration',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='feed',
            old_name='fit_image',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='feed',
            old_name='fit_title',
            new_name='title',
        ),
    ]
