# Generated by Django 3.1.5 on 2021-03-22 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitfeed', '0005_auto_20210322_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='duration',
            field=models.DurationField(),
        ),
    ]
