# Generated by Django 3.1.5 on 2021-03-16 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210315_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitprofile',
            name='img',
            field=models.ImageField(default='profile.png', upload_to='media/fit_profile_pic'),
        ),
    ]
