# Generated by Django 3.1.5 on 2021-03-16 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210316_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitprofile',
            name='img',
            field=models.ImageField(default='profile.png', upload_to='media'),
        ),
    ]
